### ISSUE TITLE
Use modern JavaScript

### ISSUE THREAD

**Issue by AwokeKnowing** [yusufhilmi/client-vector-search#11]
while typescript is popular for legacy reasons (it came out when js had no classes/modules and people were using babel transpile anyways for browsers), the reach and longevity of this codebase would be better served by not having dependency on the whole typescript build system.  Given this is for a 'browser native' capability, the code would be better developed as browser native. 
The value of having the code that runs be the same code that is developed should not be discarded. Built using native browser JS tech should be a badge of honor and is certainly 'feasible' with a library of this size.

**Comment by yusufhilmi** [comment]
ure welcome to open a PR
