### ISSUE TITLE
Model can't be found

### ISSUE THREAD

**Issue by furkanksl** [yusufhilmi/client-vector-search#5]
I am getting this error in
 [https://clientvectorsearch.com/](https://clientvectorsearch.com/) when it tries to load model.

<img width="486" alt="Screenshot 2023-11-13 at 8 46 25 PM" src="https://github.com/yusufhilmi/client-vector-search/assets/49058467/e0f3a88e-b3e7-4fd3-af45-2ae7f53cc546">

**Comment by yusufhilmi** [comment]
Yo, we fixed that. If ure running into same issue fix it like below:

```ts
import { initializeModel } from "client-vector-search"
...
  useEffect(() => {
    try {
      initializeModel();
    } catch (e) {
      console.log(e);
    }
  }, []);
```
