### ISSUE TITLE
Too much memory usage

### ISSUE THREAD

**Issue by furkanksl** [yusufhilmi/client-vector-search#6]
5k+ takes too much space in memory, just create batches between 2k-5k. 

I have 30k vectors and I cannot use indexDb. Keeping the index in memory does not make sense.

<img width="1232" alt="Screenshot 2023-11-13 at 8 54 18 PM" src="https://github.com/yusufhilmi/client-vector-search/assets/49058467/5b062478-1cdf-4e92-bebf-35c6dd957b0a">

**Comment by yusufhilmi** [comment]
We have partitioned indexedDB search coming up soon!

**Comment by mksglu** [comment]
Hi @furkanksl , we are working on this feature. Thanks for your feedback!
