### ISSUE TITLE
It may be great if combine `client-vector-search` with `browser-ai`

### ISSUE THREAD

**Issue by shunnNet** [yusufhilmi/client-vector-search#8]
Hello, I am Net Chen. A frontend developer from Taiwan.

I am working on the package called `browser-ai` recently.

The goal of this package is to run applications like `Langchain` in the browser, but aiming for simplicity. Its main features include the ability to directly convert routes or DOM into prompts, interact with LLM for Q&A, and even perform web navigation. It can also work in conjunction with `transformer.js`.

When dealing with many pages and DOM elements, the need for a vector index arises. As I began searching for a browser-side solution, I came across `client-vector-search`, which turned out to be the ideal package I was looking for.

I want to express my gratitude for creating this package.

Though I haven't started the integration yet, I've written a small example demonstrating how they can be combined.

If you are willing, you can visit the [browser-ai repository's](https://github.com/shunnNet/browser-ai) `example/qa/pages/PageIndex.vue` directory to see how they are integrated.

To run the example, follow these steps: 
1. Run `pnpm install` at root directory
2. Run `pnpm build` at root directory 
3. cd to `example/qa`
4. Create `.env` file at `example/qa` and set env variable `VITE_OPENAI_API_KEY=<your-openai-key>`
5. and run `pnpm dev`
6. Open `localhost:5173`
7. Open the console
8. Type some question like `How to setup agent` in `input` at top of page then click then button.
9. You will see the answer and the page should be scrolled to the related element.

**Comment by yusufhilmi** [comment]
seems like you already made the integration. are there any bugs and improvements we can help with?

**Comment by shunnNet** [comment]
I haven't found any helpful suggestions yet. I think I just want to express my feelings about discovering this project. Sorry for not bringing any constructive ideas.

**Comment by yusufhilmi** [comment]
no, thats alright. thanks for the kind words. hit me up on twitter and lets go through your project. would love to help. 
@yusufhilmi_
