### ISSUE TITLE
 Allow the `.update` method to update only attributes other than embedding.

### ISSUE THREAD

**Issue by shunnNet** [yusufhilmi/client-vector-search#9]
I hope to implement a functionality similar to **soft delete**. The approach would involve directly updating certain attributes of the object, such as setting `deleted` to `true`. However, the current `.update(filter, vector)` method seems challenging to achieve this. The vector parameter requires the `embedding` attribute; otherwise, an error will be thrown. This necessitates storing the same vector externally to achieve the desired result.

Perhaps I could submit a Pull Request to allow updating only attributes other than embedding?

**Comment by yusufhilmi** [comment]
yup. go ahead and open the pr. should be as easy as making embedding param optional and not rewriting it.
